package cnk.air_clientcommercialscalculationengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EntityDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String entityType;
   private java.lang.String entityName;
   private java.lang.String entityMarket;
   private java.lang.String parentEntityName;
   private java.lang.String entityStatus;
   private java.lang.String selectedRow;
   private java.lang.String childEntityName;
   private java.util.List<cnk.air_clientcommercialscalculationengine.CommercialHead> commercialHeadDetails;

   private java.util.List<java.lang.String> commercialsApplied;

   private java.util.List<cnk.air_clientcommercialscalculationengine.RetentionCommercialDetails> retentionCommercialDetails;

   public EntityDetails()
   {
   }

   public java.lang.String getEntityType()
   {
      return this.entityType;
   }

   public void setEntityType(java.lang.String entityType)
   {
      this.entityType = entityType;
   }

   public java.lang.String getEntityName()
   {
      return this.entityName;
   }

   public void setEntityName(java.lang.String entityName)
   {
      this.entityName = entityName;
   }

   public java.lang.String getEntityMarket()
   {
      return this.entityMarket;
   }

   public void setEntityMarket(java.lang.String entityMarket)
   {
      this.entityMarket = entityMarket;
   }

   public java.lang.String getParentEntityName()
   {
      return this.parentEntityName;
   }

   public void setParentEntityName(java.lang.String parentEntityName)
   {
      this.parentEntityName = parentEntityName;
   }

   public java.lang.String getEntityStatus()
   {
      return this.entityStatus;
   }

   public void setEntityStatus(java.lang.String entityStatus)
   {
      this.entityStatus = entityStatus;
   }

   public java.lang.String getSelectedRow()
   {
      return this.selectedRow;
   }

   public void setSelectedRow(java.lang.String selectedRow)
   {
      this.selectedRow = selectedRow;
   }

   public java.lang.String getChildEntityName()
   {
      return this.childEntityName;
   }

   public void setChildEntityName(java.lang.String childEntityName)
   {
      this.childEntityName = childEntityName;
   }

   public java.util.List<cnk.air_clientcommercialscalculationengine.CommercialHead> getCommercialHeadDetails()
   {
      return this.commercialHeadDetails;
   }

   public void setCommercialHeadDetails(
         java.util.List<cnk.air_clientcommercialscalculationengine.CommercialHead> commercialHeadDetails)
   {
      this.commercialHeadDetails = commercialHeadDetails;
   }

   public java.util.List<java.lang.String> getCommercialsApplied()
   {
      return this.commercialsApplied;
   }

   public void setCommercialsApplied(
         java.util.List<java.lang.String> commercialsApplied)
   {
      this.commercialsApplied = commercialsApplied;
   }

   public java.util.List<cnk.air_clientcommercialscalculationengine.RetentionCommercialDetails> getRetentionCommercialDetails()
   {
      return this.retentionCommercialDetails;
   }

   public void setRetentionCommercialDetails(
         java.util.List<cnk.air_clientcommercialscalculationengine.RetentionCommercialDetails> retentionCommercialDetails)
   {
      this.retentionCommercialDetails = retentionCommercialDetails;
   }

   public EntityDetails(
         java.lang.String entityType,
         java.lang.String entityName,
         java.lang.String entityMarket,
         java.lang.String parentEntityName,
         java.lang.String entityStatus,
         java.lang.String selectedRow,
         java.lang.String childEntityName,
         java.util.List<cnk.air_clientcommercialscalculationengine.CommercialHead> commercialHeadDetails,
         java.util.List<java.lang.String> commercialsApplied,
         java.util.List<cnk.air_clientcommercialscalculationengine.RetentionCommercialDetails> retentionCommercialDetails)
   {
      this.entityType = entityType;
      this.entityName = entityName;
      this.entityMarket = entityMarket;
      this.parentEntityName = parentEntityName;
      this.entityStatus = entityStatus;
      this.selectedRow = selectedRow;
      this.childEntityName = childEntityName;
      this.commercialHeadDetails = commercialHeadDetails;
      this.commercialsApplied = commercialsApplied;
      this.retentionCommercialDetails = retentionCommercialDetails;
   }

}