package cnk.air_clientcommercialscalculationengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FlightDetails implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public FlightDetails() {
    }

}