package cnk.air_clientcommercialscalculationengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PassengerDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String passengerType;
   private double baseValue;
   private cnk.air_clientcommercialscalculationengine.FareBreakUp fareBreakUp;
   private java.util.List<cnk.air_clientcommercialscalculationengine.CommercialDetails> commercialDetails;

   public PassengerDetails()
   {
   }

   public java.lang.String getPassengerType()
   {
      return this.passengerType;
   }

   public void setPassengerType(java.lang.String passengerType)
   {
      this.passengerType = passengerType;
   }

   public double getBaseValue()
   {
      return this.baseValue;
   }

   public void setBaseValue(double baseValue)
   {
      this.baseValue = baseValue;
   }

   public cnk.air_clientcommercialscalculationengine.FareBreakUp getFareBreakUp()
   {
      return this.fareBreakUp;
   }

   public void setFareBreakUp(
         cnk.air_clientcommercialscalculationengine.FareBreakUp fareBreakUp)
   {
      this.fareBreakUp = fareBreakUp;
   }

   public java.util.List<cnk.air_clientcommercialscalculationengine.CommercialDetails> getCommercialDetails()
   {
      return this.commercialDetails;
   }

   public void setCommercialDetails(
         java.util.List<cnk.air_clientcommercialscalculationengine.CommercialDetails> commercialDetails)
   {
      this.commercialDetails = commercialDetails;
   }

   public PassengerDetails(
         java.lang.String passengerType,
         double baseValue,
         cnk.air_clientcommercialscalculationengine.FareBreakUp fareBreakUp,
         java.util.List<cnk.air_clientcommercialscalculationengine.CommercialDetails> commercialDetails)
   {
      this.passengerType = passengerType;
      this.baseValue = baseValue;
      this.fareBreakUp = fareBreakUp;
      this.commercialDetails = commercialDetails;
   }

}