package cnk.air_clientcommercialscalculationengine;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RetentionCommercialDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String commercialName;
   private double commercialCalculationPercentage;
   private double commercialCalculationAmount;
   private java.lang.String commercialCurrency;
   private java.lang.String commercialFareComponent;
   private double retentionPercentage;
   private double retentionAmountPercentage;
   private double commercialAmount;
   private double remainingPercentageAmount;
   private double remainingAmount;

   public RetentionCommercialDetails()
   {
   }

   public java.lang.String getCommercialName()
   {
      return this.commercialName;
   }

   public void setCommercialName(java.lang.String commercialName)
   {
      this.commercialName = commercialName;
   }

   public double getCommercialCalculationPercentage()
   {
      return this.commercialCalculationPercentage;
   }

   public void setCommercialCalculationPercentage(
         double commercialCalculationPercentage)
   {
      this.commercialCalculationPercentage = commercialCalculationPercentage;
   }

   public double getCommercialCalculationAmount()
   {
      return this.commercialCalculationAmount;
   }

   public void setCommercialCalculationAmount(
         double commercialCalculationAmount)
   {
      this.commercialCalculationAmount = commercialCalculationAmount;
   }

   public java.lang.String getCommercialCurrency()
   {
      return this.commercialCurrency;
   }

   public void setCommercialCurrency(java.lang.String commercialCurrency)
   {
      this.commercialCurrency = commercialCurrency;
   }

   public java.lang.String getCommercialFareComponent()
   {
      return this.commercialFareComponent;
   }

   public void setCommercialFareComponent(
         java.lang.String commercialFareComponent)
   {
      this.commercialFareComponent = commercialFareComponent;
   }

   public double getRetentionPercentage()
   {
      return this.retentionPercentage;
   }

   public void setRetentionPercentage(double retentionPercentage)
   {
      this.retentionPercentage = retentionPercentage;
   }

   public double getRetentionAmountPercentage()
   {
      return this.retentionAmountPercentage;
   }

   public void setRetentionAmountPercentage(double retentionAmountPercentage)
   {
      this.retentionAmountPercentage = retentionAmountPercentage;
   }

   public double getCommercialAmount()
   {
      return this.commercialAmount;
   }

   public void setCommercialAmount(double commercialAmount)
   {
      this.commercialAmount = commercialAmount;
   }

   public double getRemainingPercentageAmount()
   {
      return this.remainingPercentageAmount;
   }

   public void setRemainingPercentageAmount(double remainingPercentageAmount)
   {
      this.remainingPercentageAmount = remainingPercentageAmount;
   }

   public double getRemainingAmount()
   {
      return this.remainingAmount;
   }

   public void setRemainingAmount(double remainingAmount)
   {
      this.remainingAmount = remainingAmount;
   }

   public RetentionCommercialDetails(java.lang.String commercialName,
         double commercialCalculationPercentage,
         double commercialCalculationAmount,
         java.lang.String commercialCurrency,
         java.lang.String commercialFareComponent,
         double retentionPercentage, double retentionAmountPercentage,
         double commercialAmount, double remainingPercentageAmount,
         double remainingAmount)
   {
      this.commercialName = commercialName;
      this.commercialCalculationPercentage = commercialCalculationPercentage;
      this.commercialCalculationAmount = commercialCalculationAmount;
      this.commercialCurrency = commercialCurrency;
      this.commercialFareComponent = commercialFareComponent;
      this.retentionPercentage = retentionPercentage;
      this.retentionAmountPercentage = retentionAmountPercentage;
      this.commercialAmount = commercialAmount;
      this.remainingPercentageAmount = remainingPercentageAmount;
      this.remainingAmount = remainingAmount;
   }

}